### ISSUE TITLE
problem Port

### ISSUE THREAD

**Issue by morganplancot** [jammsen/docker-sons-of-the-forest-dedicated-server#14]
Good morning,

I have a problem when the server turns on when testing the ports it tells me that they are not open.
my ports are open, what should I do?

**Comment by jammsen** [comment]
Hey did you read #5 ?

**Comment by morganplancot** [comment]
Good morning,

indeed now the server starts I can see the server on steam I managed to add it to my favorites but impossible to connect

**Comment by morganplancot** [comment]
I don't know if it can help you

Connection:1
Dedicated server connection with auth ticket
Steam auth successful for client 2 with steam id 76561198023441537
GetMatchingBlobTransportRemote: connection [Connection [EndPoint 85.190.89.227:57393 | 6178474570291404849]] not mapped
New bolt client connected [Connection [EndPoint 85.190.89.227:57393 | 6178474570291404849]], generated blob sync token = 14237975063250015262
Fps Limiter set to 60
ValidateAuthTicketResponse success for 76561198023441537
