### ISSUE TITLE
Connection to the server

### ISSUE THREAD

**Issue by morganplancot** [jammsen/docker-sons-of-the-forest-dedicated-server#15]
Hello my sound of the forest server is well started I see it in the list of servers, but when I want to connect I put my password but it remains on current connection
Has anyone had this problem before?

**Comment by jammsen** [comment]
Hello, this seems to be a "Dedicated Server" problem nothing with the Docker-Image which is offered here.

Please try to get support to the game-server here and good luck:
https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/?tscn=1689154372

**Comment by jammsen** [comment]
@morganplancot if this issue is done, please close the issue

**Comment by jammsen** [comment]
Closed because of inactivity
