### ISSUE TITLE
i would like to activate server commands

### ISSUE THREAD

**Issue by dralos** [jammsen/docker-sons-of-the-forest-dedicated-server#16]
Hello,  
I don't know if this counts as an issue, but is there any way to activate server commands for a player  o just to execute them from the console.

PS: thank you for creating this docker is amazing
Thanks in advance.

**Comment by jammsen** [comment]
Hello @dralos thank you for the feedback.
This Github-Repo/Issues is for the part taking the server and make it runable with Linux and Docker.

What you seek is more like a general support. This forum post of the developers would be more suitable for this:

https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/
