### ISSUE TITLE
Issue loading

### ISSUE THREAD

**Issue by RealFascinated** [jammsen/docker-sons-of-the-forest-dedicated-server#2]
I am having an issue loading the server. https://haste.fascinated.cc/amumofeviv.sql

**Comment by jammsen** [comment]
Hey @RealFascinated 
thats weird, almost anything doing anything is throwing a permission denid error on your side, this should not happen.

Can you explain your configuration, host-settings and Docker-Version+Settings please?

**Comment by jammsen** [comment]
Ping @RealFascinated

**Comment by NarpasSword** [comment]
I had the same permissions issue initially. It turned out to be selinux in enforce mode blocking the docker volumes from being created. Just setting selinux to permissive mode got it working.

**Comment by jammsen** [comment]
Hey @NarpasSword thanks for sharing, but the OP isnt answering so im gonna in-activity close this now.
