### ISSUE TITLE
Can't see Server in LAN

### ISSUE THREAD

**Issue by JS-E** [jammsen/docker-sons-of-the-forest-dedicated-server#20]
**Important information**
Please understand you are asking for support for the Docker-Image and Docker-Container. Im NOT the creator of the Dedicated-Gamserver itself, i'm not involved in programming that. If you need help for that,  you might want to ask here for topics related to that: https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/ 

**Describe the bug**
I cannot see my server in the LAN list when i host it on a server within my home

**To Reproduce**
1. I run the docker container on my local server
2. I ensure LAN only is true
3. I allow all traffic to and from my pc to server (to ensure it's not my firewall)
4. I run SOTF on my PC and go to join, selecting LAN
5. Nothing shows

**Expected behavior**
I expect my server to show up in the list

**Screenshots**

**Software (please complete the following information):**
[Server]
 - OS: OpenMediaVault

[PC]
-OS: Windows 11

**Hardware (please complete the following information):**
 - vCPU: 6 CPUS
 - RAM:  8GB
 - Disk: 2TB

**Additional context**
I can see network activity where SOTF is broadcasting on my network, but it seems as though my server isn't reporting back

**Comment by JS-E** [comment]
I've just managed to fix this and i can confirm this isn't a problem with this docker image. I noticed that the Sons of the forest network broadcast was on the wrong network adapter, so once disabling all adapters apart from my ethernet i could finally see my LAN server. Hopefully this helps someone else if they are getting the same problem

**Comment by jammsen** [comment]
Hey @JS-E very nice, thanks for the problem and solution and sorry i was very busy this week and couldnt be of help in a timely manner.
