### ISSUE TITLE
Docker images save file editing

### ISSUE THREAD

**Issue by Junnyjun** [jammsen/docker-sons-of-the-forest-dedicated-server#26]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Is it possible to revive NPC that help me get resources?

i attached some links for understand
https://www.rockpapershotgun.com/sons-of-the-forest-revive-companions
https://thenerdstash.com/how-to-find-save-file-location-in-sons-of-the-forest/

addition ) 
the path of the savefile is /sonsoftheforest/userdata/Saves/DedicatedServer/Multiplayer
~~but i cant find any GameStateSaveData.json file~~

i found the SaveData.json
However, the file is in a compressed file, so you'll need to check if your changes will be applied when you recompress it.
If I modify the SaveData.json and recompress it to the same path, will it take effect?

logs ) attach some bash log for understand to solve
```
path : /sonsoftheforest/userdata/Saves/DedicatedServer/Multiplayer/0000000001

file list :  
Dedicated_Server_Autosave_2023-09-05_16_11_58_Slot__1.name
SaveData.zip
SaveDataThumbnail.png

zip inside files : 
ConstructionsSaveData.json                                  GameStateSaveData.json                             RainCatcherManagerSaveData.json            ScrewStructureNodeInstancesSaveData.json
CookingSaveManagerSaveData.json                             GardenPlotManagerSaveData.json                     Resin3dPrinter_BunkerASaveData.json        ScrewTrapsSaveData.json
Dedicated_Server_Autosave_2023-09-05_16_01_58_Slot__1.name  HotkeysSaveData.json                               Resin3dPrinter_BunkerBSaveData.json        ScrewTreeLinkersSaveData.json
FiresSaveData.json                                          MultiplayerPlayerRolesSaveData.json                Resin3dPrinter_EntertainmentSaveData.json  StructureDestructionSaveData.json
FreeFormFreeLinksManagerSaveData.json                       PlayerArmourSystemSaveData.json                    Resin3dPrinter_ResidentialSaveData.json    WeatherSystemSaveData.json
FreeFormStructureLinkerManagerSaveData.json                 PlayerClothingSystemSaveData.json                  SaveData.json                              WorldItemManagerSaveData.json
FreeFormTreeStructuresSaveData.json                         PlayerInventorySaveData.json                       SaveData.zip                               WorldObjectLocatorManagerSaveData.json
FurnitureStorageSaveData.json                               PlayerRetrieveDroppedInventoryActionSaveData.json  SaveDataThumbnail.png                      ZipLineManagerSaveData.json
GameSetupSaveData.json                                      PlayerStateSaveData.json                           ScrewStructureInstancesSaveData.json
```

### Desired behavior

revive NPC by editing saveData.json

### Links to screenshots

Attach relevant links instead of screenshots 

https://www.rockpapershotgun.com/sons-of-the-forest-revive-companions

### To Reproduce

1. 'NPC dies'
2. editing 'SaveData.json'
3. Recompression
4. See revive NPC

### Software setup

- OS: linux ( intel ) 
- Docker: docker version
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:23 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:23 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Hardware setup

- vCPU: 4core
- RAM: 24GB
- Disk: 50GB

**Comment by jammsen** [comment]
Hey @Junnyjun 
i have no clue about that topic i only support the docker-image - Try the Steam-Forum for this topic:
https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/

**Comment by gitzec** [comment]
I mean... You answered your own question. It is right in your first link Find the save file, edit it and the NPCs are back alive. Since the save is dynamic data it sits on one of the volumes you mounted into the container. It should be inside /sonsoftheforest/userdata/Saves/... I guess.

But as our boss in here wrote: This is not related to the docker image.

**Comment by jammsen** [comment]
@gitzec Im the boss of nobody 😄 
Sorry, but my text should not come across as bossy or high'n'mighty.
I simply dont know about this topic and would refer to the Steam-Forum where the base of people to ask is far greater than this issue-tracker.

**Comment by Junnyjun** [comment]
> I mean... You answered your own question. It is right in your first link Find the save file, edit it and the NPCs are back alive. Since the save is dynamic data it sits on one of the volumes you mounted into the container. It should be inside /sonsoftheforest/userdata/Saves/... I guess.
> 
> But as our boss in here wrote: This is not related to the docker image.



> @gitzec Im the boss of nobody 😄 Sorry, but my text should not come across as bossy or high'n'mighty. I simply dont know about this topic and would refer to the Steam-Forum where the base of people to ask is far greater than this issue-tracker.

I will try it, thanks a lot.
Thanks for making such good images like this, I'm having fun with it !
