### ISSUE TITLE
Wine error during startup : poll_users[user] == fd' failed

### ISSUE THREAD

**Issue by Fredowulf** [jammsen/docker-sons-of-the-forest-dedicated-server#27]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Sometimes the docker startup stops with a wine error : 
- wineserver: server/fd.c:1644: set_fd_events: Assertion `poll_users[user] == fd' failed.

My compose 
        version: '3.9'
        services:
          sons-of-the-forest-dedicated-server:
            container_name: sons-of-the-forest-dedicated-server
            image: jammsen/sons-of-the-forest-dedicated-server:latest
            restart: always
            environment:
              ALWAYS_UPDATE_ON_START: 1
            ports:
              - 8766:8766/udp
              - 27016:27016/udp
              - 9700:9700/udp
            volumes:
              - /home/sonsoftheforest/steamcmd:/steamcmd
              - /home/sonsoftheforest/game:/sonsoftheforest
              - /home/sonsoftheforest/winedata:/winedata

### Desired behavior

I'd like the server to boot without issue. 
Every day around 0400 I reboot it, I'd like to be sure that my friends can play on it. 

### To Reproduce

1. Go to portainer
2. Click on start stack
3. Watch logs of the container
4. See error : 
[nouveau 1.txt](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/files/12723270/nouveau.1.txt)

### Software setup

- OS: ubuntu 22 04 3
- Docker: up to date ; managed by portainer 2 18 4

### Hardware setup

- vCPU: I5 12600
- RAM: 64go
- Disk: 2To SSD

### Additional context

Thank you so much for your work !

As noted this behavior is not constant, sometimes the server starts without trouble ; but sometimes it get stuck at this wine error.

**Comment by jammsen** [comment]
Hey @Fredowulf 
That sometimes that can happen, it happend to me too, im not sure why it does that and which use-case isnt covered in my shell-scripts that cover the starts to solve this random/weird behavior.

Soluton for me was a "cronjob" at time 04:00 which does:
- docker-compose down -v
- docker-compose up -d

After that i never once encounterd that problem because every restart is a reprovsion freshly and maybe some volume/caching hick-ups are gone.

I never found a way to reproduce the error to analyse and solve it. 
Sorry to not have anything better for you.

**Comment by Fredowulf** [comment]
Thank you so much for this work around. I'll try this tomorrow morning.
Kind regards,
F.

**Comment by Fredowulf** [comment]
Hello,
It worked perfectly today : thank you again !
Have a good day,
F.

**Comment by kevinfengcs88** [comment]
> Hey @Fredowulf That sometimes that can happen, it happend to me too, im not sure why it does that and which use-case isnt covered in my shell-scripts that cover the starts to solve this random/weird behavior.
> 
> Soluton for me was a "cronjob" at time 04:00 which does:
> 
>     * docker-compose down -v
> 
>     * docker-compose up -d
> 
> 
> After that i never once encounterd that problem because every restart is a reprovsion freshly and maybe some volume/caching hick-ups are gone.
> 
> I never found a way to reproduce the error to analyse and solve it. Sorry to not have anything better for you.

Typically restarting it a few times would get it working for me, but if >5 restarts didn't fix it, for some reason, changing the .cfg file (where you define the server name, password, etc.) enabled the server to start up. Specifically I changed the name of the server

**Comment by jammsen** [comment]
@kevinfengcs88 Eh this issue was closed 1 year ago?
