### ISSUE TITLE
Stuck in loop installing - steambootstrapper

### ISSUE THREAD

**Issue by iamdaaan** [jammsen/docker-sons-of-the-forest-dedicated-server#28]
### Current behavior

The docker container cannot seem to find a file called steambootstrapper_english.txt?
It doesn't seem to be able to even install the game server

### To Reproduce

1. Copy the Docker run command
2. View container logs

### Software setup

- OS: Windows 11
- Docker: Docker Desktop v4.24.2

### Hardware setup

- CPU: i9-10900F 
- RAM: 32GB

Docker Desktop Logs:
2023-10-24 11:53:51 >>> Doing a fresh install of the gameserver
2023-10-24 11:53:55 Redirecting stderr to '/root/Steam/logs/stderr.txt'
2023-10-24 11:53:55 Looks like steam didn't shutdown cleanly, scheduling immediate update check
2023-10-24 11:53:55 ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
2023-10-24 11:53:55 [  0%] Checking for available update...
2023-10-24 11:53:55 [  0%] Download Complete.
2023-10-24 11:53:55 [----] Applying update...
2023-10-24 11:53:55 [----] Extracting package...
2023-10-24 11:53:55 [----] Extracting package...
2023-10-24 11:53:55 [----] Extracting package...
2023-10-24 11:53:55 [----] Extracting package...
2023-10-24 11:53:55 [----] Installing update...
2023-10-24 11:53:55 [----] Cleaning up...
2023-10-24 11:53:55 [----] Failed to remove temporary unzip folder, continuing anyway
2023-10-24 11:53:55 [----] Update complete, launching...
Just restarts the same loop after this...

**Comment by gitzec** [comment]
Idk, maybe you need to switch to Linux containers on Docker Desktop on Windows?

**Comment by iamdaaan** [comment]
Im already using WSL containers instead of Hyper-V, and I'm planning on migrating to a server PC at some point so was wanting to get Docker containers ready to move across

**Comment by jammsen** [comment]
Hey have you tried the Windows equavilent of Linux's "chmod 777 directory" on your directories that you try to volumen-mount?

**Comment by jammsen** [comment]
@iamdaaan is the problem solved? Can this issue be closed?

**Comment by jammsen** [comment]
Closed because of inactivity

**Comment by PontyJohnty** [comment]
Sorry appreciate this is closed, but i had this problem on Docker Desktop via Windows 11 (WSL) and also on Synology NAS.  Using Portainer on both.

I was able to resolve both issues by binding to a volume as follows with docker compose.

~~~
    volumes:
     - sons-of-the-forest-1:/sonsoftheforest
     - sons-of-the-forest-1:/steamcmd
     - sons-of-the-forest-1:/winedata

volumes:
  sons-of-the-forest-1:
~~~
To edit the dedicated server config file is easy enough in windows, you just need to find the volume, which for me was:

\\wsl.localhost\docker-desktop-data\data\docker\volumes\sons-of-the-forest-ds_sons-of-the-forest-1

Synology NAS was more tricky and i ended up installing filebrowser in docker with "srv" set to the volume container manager was on and find it through there.

I hope this helps anyone in this position.

**Comment by jammsen** [comment]
> Sorry appreciate this is closed

If someone steals a closed thread i might get a little angry or 🙄 but not for posting solutions, your fine! So thanks for helping!

> Synology NAS was more tricky and i ended up installing filebrowser in docker with "srv" set to the volume container manager was on and find it through there.

Please be aware, that at least to my knowledge, that most Synology or QNAP NAS'es dont even have more then 4GB of RAM. But you need at least 6GB of RAM for this dedicated server alone to my extensive testing at that time. See here [#7 ](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/issues/7#issuecomment-1611097781)

**Comment by PontyJohnty** [comment]
Hey no problem; thank you for taking the time to containerise this!

Can also confirm, 6GB used on my synology.  I have 20GB in total, so plenty of headroom.
