### ISSUE TITLE
Failed to get Public IP

### ISSUE THREAD

**Issue by h1ght** [jammsen/docker-sons-of-the-forest-dedicated-server#30]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Failing to start the server, because it cant get public IP off steam. Untill now, i havent read anything in the last time in the sons dedicated server thread so far. 

#DSE Invalid public ip [0.0.0.0]
#DSE [Self-Tests] [Networking] Failed to get public ip from Steam.
#DSE [Self-Tests] Please restart the server.

### Desired behavior

Should obtain the public IP

### To Reproduce

Start it via compose

### Software setup

- OS: Linux Debian-1106-bullseye-amd64-base 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
- Docker:
- Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Hardware setup

- CPU:  i7-8700k
- RAM:  64GB
- Disk: 500GB SSD
-  Hetzner dedicated server

### Additional context

i tried "network_mode: host" via compose, same error. it worked couple of days before. so dunno.

**Comment by jammsen** [comment]
Hello @h1ght 
The same problem was already solved in #5 - Look in there for "SkipNetworkAccessibilityTest"
