### ISSUE TITLE
Container crashes after #DSL Loading progress: 19

### ISSUE THREAD

**Issue by Jonny-S-River** [jammsen/docker-sons-of-the-forest-dedicated-server#31]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Container seem to crash after the message #DSL Loading progress: 19

### Desired behavior

Server should load normally

### To Reproduce

- Run Dockercompose as in the readme

### Software setup

- OS: Ubuntu 22.04
- Docker: 24.0.5, build 24.0.5-0ubuntu1~22.04.1

### Hardware setup

- vCPU: 4
- RAM: 4
- Disk: 80GB

### Additional context

sons-of-the-forest-dedicated-server    | #DSL Loading progress: 13
sons-of-the-forest-dedicated-server    | #DSL Loading progress: 16
sons-of-the-forest-dedicated-server    | #DSL Loading progress: 19
sons-of-the-forest-dedicated-server    | Couldn't create a Convex Mesh from source mesh "ShortPotMesh" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
sons-of-the-forest-dedicated-server    | #DSL Loading progress: 19
sons-of-the-forest-dedicated-server    | #DSL Loading progress: 19
sons-of-the-forest-dedicated-server    | /usr/bin/servermanager.sh: line 84:   169 Killed                  wine64 /sonsoftheforest/SonsOfTheForestDS.exe -userdatapath $USERDATA_PATH

**Comment by Jonny-S-River** [comment]
After Trying to start the Server manually i get this message:

src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp (2124) : Assertion Failed: SteamnetworkingSocke
ts service thread waited 95ms for lock!  This directly adds to network latency!  It could be a bug, but it's usually cau
sed by general performance problem such as thread starvation or a debug output handler taking too long.#DSL Loading prog
ress: 19

src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp (2124) : Assertion Failed: SteamnetworkingSocke
ts service thread waited 95ms for lock!  This directly adds to network latency!  It could be a bug, but it's usually cau
sed by general performance problem such as thread starvation or a debug output handler taking too long.
Killed



This seems to be a Performance issue right?

**Comment by jammsen** [comment]
Hello @Jonny-S-River,
i dont think i ever had this problem before. You might want to look at this ( https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/issues/7#issuecomment-1611097781 ) for MSR (Minimum System Requirements).

Maybe that solves your problem.

**Comment by gitzec** [comment]
I think you run out of memory. this is the startup process of my container:
 
![startup](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/27860439/361d4708-fae3-4c97-b49f-59f94810f78d)

The container asks the cluster for 4 CPUs and 8 GB RAM.

**Comment by Jonny-S-River** [comment]
Hi, i managed to get my hands on a bigger VM With dedicated cores and more RAM. 4 Cores 8GB Ram and that really seems to be it. I didnt throw enough money at it ;)
