### ISSUE TITLE
Server is showing up as Invalid

### ISSUE THREAD

**Issue by ghost** [jammsen/docker-sons-of-the-forest-dedicated-server#32]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Issue is similar to #22 except I am using the latest version of docker.  Container starts correctly and dedicated server does start up and is ready when looking at logs, however the server shows up in the dedicated server list with IP:PORT, cannot join, connecting Direct and inputting in IP:PORT results in Game Server Not Found.  UFW is not active on host.  Host is on a public IP and is not behind a service provider firewall.

### Desired behavior

Game shows up in server list with servername

### To Reproduce

Fresh install of ubuntu 22.04LTS
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

cd ~
sudo mkdir srv
cd srv
sudo mkdir sonsoftheforest
cd sonsoftheforest
sudo mkdir game
sudo mkdir steamcmd

Create docker-compose.yml file
sudo docker compose up -d

stop container, edit dedicatedserver.cfg

start container, see in the log that it is parsing dedicatedserver.cfg correctly, server log ends with:
#DSL Autosave complete. Time: 2023-11-16 23:57:10 Slot: 1
#DSL Server empty, idling...
#DSL Set target framerate: 5
#DSL Dedicated server loaded.

### Software setup

- OS: Ubuntu 22.04 LTS
- Docker:  Docker version 24.0.7, build afdd53b

### Hardware setup

- vCPU: 8
- RAM:  16
- Disk: 80

**Comment by jammsen** [comment]
Are you running this as root or as a user?
Im confused because of the sudo heavy usage, you can just add your user to the docker group, google "usermod -aG docker" related to that.

**Comment by rmelly78** [comment]
Running as regular user! Will try that and report back

**Comment by jammsen** [comment]
Closed because of inactivity
