### ISSUE TITLE
Failed to launch the container

### ISSUE THREAD

**Issue by ValcasaraBryan** [jammsen/docker-sons-of-the-forest-dedicated-server#34]
### Have you read the Important information text above

- [x] Yes i did

### Current behavior

I want create a dedicated server on my personnal NAS, this NAS have synology OS and a Container Manager for install images.
I have download your image put the compose.yaml and when I launch the container I have some erreurs.

### Desired behavior

That the server was launched

### Links to screenshots

![docker 2](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/31510683/88f8359f-ffd0-4313-a97d-c540ec1f4119)
![docker 1](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/31510683/7344f226-1f33-4811-80ea-ad52c6612ce3)

next images seeing bottom to top :
![docker 5](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/31510683/ac888abe-f0e5-460d-808e-c1ddf1417db9)
![docker 4](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/31510683/5517063c-4570-415b-975d-e2b802d72d98)
![docker 3](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/31510683/0a6dd753-eab0-447d-8d6e-f51ad4a59603)

### Software setup

- OS: DSM 7.2.1-69057 Update 2
- Docker: Container Manager v20.10.23-1413 - Developped by Docker Inc.

### Hardware setup

- Model NAS : DS920+
- CPU: INTEL Celeron J4125
- vCPU: Set to unlimited for the container
- RAM: 4096 Mo
- Disk: 2To

**Comment by jammsen** [comment]
Closed because of inactivity
