### ISSUE TITLE
Admin console not working

### ISSUE THREAD

**Issue by gligi** [jammsen/docker-sons-of-the-forest-dedicated-server#35]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Admin console not working

### Desired behavior

The console should work if user (steam) id is added to the ownerswhitelist.txt

### To Reproduce

- edit ownerswhitelist.txt 
- add steam id
- save
- restart server
- use chat window to enable admin (cheatstick)

### Software setup

- OS: win 11
- Docker: this one

### Hardware setup

- vCPU: 10
- RAM: 32
- Disk: 1Tb

### Additional context

Any idea why this is not working?

**Comment by gligi** [comment]
it works with US keyboard active

**Comment by jammsen** [comment]
Glad it works, not really a Docker-Image error though 👍
