### ISSUE TITLE
Where seting the password??

### ISSUE THREAD

**Issue by williamcanon1** [jammsen/docker-sons-of-the-forest-dedicated-server#36]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Hello sir.  I need set password for game. but i dont's know how to set it .

### Desired behavior

`

### To Reproduce

`

### Software setup

`

### Hardware setup

`

### Additional context

`

**Comment by jammsen** [comment]
Hello @williamcanon1 - did you have a look at the files included?
https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/blob/master/dedicatedserver.cfg.example

**Comment by jammsen** [comment]
Hello?

**Comment by jammsen** [comment]
Closed because of incativity

**Comment by Mafyuh** [comment]
Nobody looked thru the files, there should be an env variable to set config variables

**Comment by leangermany** [comment]
?here to add the config in the example? Using docker-compose.yml

**Comment by Mafyuh** [comment]
Run find / -type f -name dedicatedserver.cfg 2>/dev/null inside the container
