### ISSUE TITLE
Synology Docker: Failing to install, failing to open SonsOfTheForestDS.exe

### ISSUE THREAD

**Issue by Inazumaa** [jammsen/docker-sons-of-the-forest-dedicated-server#39]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Hello, 
I've installed this image in to my Container Manager (docker) on my Synology NAS. I've hooked it up to some new folders and forwarded the ports. However it seems unable to download and run SonsOfTheForestDS.exe. It is able to put a couple files and folders into the root of the directories I have given it (see screenshot) but doesn't put anything into the "game" or "steamcmd" folders.

Please help. Let me know if you need any more info. I have had Valheim and 7dtd servers running from docker images with no problem.

> SOTF
date,stream,content
2024/02/13 10:55:07,stdout,wine: failed to open "/sonsoftheforest/SonsOfTheForestDS.exe": c0000135

2024/02/13 10:55:07,stdout,>>> Starting the gameserver

2024/02/13 10:55:07,stdout,0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 10:55:07,stdout,0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 10:55:07,stdout,0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 10:55:07,stdout,0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 10:55:06,stdout,[----] !!! Fatal Error: Failed to load libsteam.so

2024/02/13 10:55:06,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 10:55:06,stdout,[----] Installing update...

2024/02/13 10:55:06,stdout,[----] Installing update...

2024/02/13 10:55:06,stdout,[----] Extracting package...

2024/02/13 10:55:04,stdout,[----] Extracting package...

2024/02/13 10:55:03,stdout,[----] Extracting package...

2024/02/13 10:55:03,stdout,[----] Extracting package...

2024/02/13 10:55:03,stdout,[  0%] Download Complete.

2024/02/13 10:55:03,stdout,[  0%] Checking for available update...

2024/02/13 10:55:03,stdout,[  0%] Downloading Update...

2024/02/13 10:55:03,stdout,[----] Verifying installation...

2024/02/13 10:55:03,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 10:55:03,stdout,[----] Installing update...

2024/02/13 10:55:03,stdout,[----] Installing update...

2024/02/13 10:55:02,stdout,[----] Extracting package...

2024/02/13 10:55:01,stdout,[----] Extracting package...

2024/02/13 10:55:00,stdout,[----] Extracting package...

2024/02/13 10:55:00,stdout,[----] Extracting package...

2024/02/13 10:55:00,stdout,[----] Applying update...

2024/02/13 10:55:00,stdout,[  0%] Download Complete.

2024/02/13 10:54:59,stdout,[  0%] Checking for available update...

2024/02/13 10:54:59,stdout,ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".

2024/02/13 10:54:59,stdout,Redirecting stderr to '/root/Steam/logs/stderr.txt'

2024/02/13 10:54:59,stdout,>>> Doing an update of the gameserver

2024/02/13 10:54:59,stdout,[----] !!! Fatal Error: Failed to load libsteam.so

2024/02/13 10:54:59,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 10:54:59,stdout,[----] Installing update...

2024/02/13 10:54:59,stdout,[----] Installing update...

2024/02/13 10:54:59,stdout,[----] Extracting package...

2024/02/13 10:54:57,stdout,[----] Extracting package...

2024/02/13 10:54:56,stdout,[----] Extracting package...

2024/02/13 10:54:56,stdout,[----] Extracting package...

2024/02/13 10:54:56,stdout,[  0%] Download Complete.

2024/02/13 10:54:56,stdout,[  0%] Checking for available update...

2024/02/13 10:54:56,stdout,[  0%] Downloading Update...

2024/02/13 10:54:56,stdout,[----] Verifying installation...

2024/02/13 10:54:56,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 10:54:56,stdout,[----] Installing update...

2024/02/13 10:54:56,stdout,[----] Installing update...

2024/02/13 10:54:55,stdout,[----] Extracting package...

2024/02/13 10:54:54,stdout,[----] Extracting package...

2024/02/13 10:54:52,stdout,[----] Extracting package...

2024/02/13 10:54:52,stdout,[----] Extracting package...

2024/02/13 10:54:52,stdout,[----] Applying update...

2024/02/13 10:54:52,stdout,[  0%] Download Complete.

2024/02/13 10:54:52,stdout,[  0%] Checking for available update...

2024/02/13 10:54:52,stdout,ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".

2024/02/13 10:54:52,stdout,Redirecting stderr to '/root/Steam/logs/stderr.txt'

### Desired behavior

For the update to work and the server to run.

### Links to screenshots

![sotf_docker_settings_1](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/19316331/540d1c3f-16d0-4d82-8d7a-88cc7fe2c2ae)
![sotf_docker_settings_2](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/19316331/2645128f-0962-4602-92f7-68b3b3f90202)
![sotf_docker_folders](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/19316331/c29800bf-1744-484e-858a-9b6ace968899)

### To Reproduce

1. Set up docker image using settings pictured
2. Click Run
3. Observe log
4. Observe that the image fails to start

### Software setup

- OS: Synology DSM 7.2.1-69057 Update 4
- Docker: 20.10.23-1437

### Hardware setup

- vCPU: INTEL Celeron J4125 2Ghz
- RAM: 12gb
- Disk: Several terabytes

**Comment by Inazumaa** [comment]
This is the full log from a freshly started image.
I've also attmpted to give Read/Write access on that folder to Everyone/thing. Same errors occur.

```
jammsen-sons-of-the-forest-dedicated-server
date,stream,content
2024/02/13 13:06:06,stdout,wine: failed to open "/sonsoftheforest/SonsOfTheForestDS.exe": c0000135

2024/02/13 13:06:06,stdout,>>> Starting the gameserver

2024/02/13 13:06:05,stdout,0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 13:06:05,stdout,0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 13:06:05,stdout,0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 13:06:05,stdout,0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

2024/02/13 13:06:05,stdout,[----] !!! Fatal Error: Failed to load libsteam.so

2024/02/13 13:06:05,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 13:06:05,stdout,[----] Installing update...

2024/02/13 13:06:05,stdout,[----] Installing update...

2024/02/13 13:06:05,stdout,[----] Extracting package...

2024/02/13 13:06:03,stdout,[----] Extracting package...

2024/02/13 13:06:02,stdout,[----] Extracting package...

2024/02/13 13:06:02,stdout,[----] Extracting package...

2024/02/13 13:06:02,stdout,[  0%] Download Complete.

2024/02/13 13:06:02,stdout,[  0%] Checking for available update...

2024/02/13 13:06:02,stdout,[  0%] Downloading Update...

2024/02/13 13:06:02,stdout,[----] Verifying installation...

2024/02/13 13:06:02,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 13:06:02,stdout,[----] Installing update...

2024/02/13 13:06:02,stdout,[----] Installing update...

2024/02/13 13:06:02,stdout,[----] Extracting package...

2024/02/13 13:06:00,stdout,[----] Extracting package...

2024/02/13 13:05:59,stdout,[----] Extracting package...

2024/02/13 13:05:59,stdout,[----] Extracting package...

2024/02/13 13:05:59,stdout,[----] Applying update...

2024/02/13 13:05:59,stdout,[  0%] Download Complete.

2024/02/13 13:05:58,stdout,[  0%] Checking for available update...

2024/02/13 13:05:58,stdout,ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".

2024/02/13 13:05:58,stdout,Redirecting stderr to '/root/Steam/logs/stderr.txt'

2024/02/13 13:05:58,stdout,>>> Doing an update of the gameserver

2024/02/13 13:05:58,stdout,[----] !!! Fatal Error: Failed to load libsteam.so

2024/02/13 13:05:58,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 13:05:58,stdout,[----] Installing update...

2024/02/13 13:05:58,stdout,[----] Installing update...

2024/02/13 13:05:58,stdout,[----] Extracting package...

2024/02/13 13:05:57,stdout,[----] Extracting package...

2024/02/13 13:05:55,stdout,[----] Extracting package...

2024/02/13 13:05:55,stdout,[----] Extracting package...

2024/02/13 13:05:55,stdout,[  0%] Download Complete.

2024/02/13 13:05:55,stdout,[  0%] Checking for available update...

2024/02/13 13:05:55,stdout,[  0%] Downloading Update...

2024/02/13 13:05:55,stdout,[----] Verifying installation...

2024/02/13 13:05:55,stdout,"[----] Failed to apply update, reverting...
"
2024/02/13 13:05:55,stdout,[----] Installing update...

2024/02/13 13:05:55,stdout,[----] Installing update...

2024/02/13 13:05:55,stdout,[----] Extracting package...

2024/02/13 13:05:53,stdout,[----] Extracting package...

2024/02/13 13:05:52,stdout,[----] Extracting package...

2024/02/13 13:05:52,stdout,[----] Extracting package...

2024/02/13 13:05:52,stdout,[----] Applying update...

2024/02/13 13:05:52,stdout,[100%] Download Complete.

2024/02/13 13:05:52,stdout,[ 99%] Downloading update (90458 of 90458 KB)...

2024/02/13 13:05:51,stdout,[ 97%] Downloading update (89996 of 90458 KB)...

2024/02/13 13:05:51,stdout,[ 96%] Downloading update (88569 of 90458 KB)...

2024/02/13 13:05:51,stdout,[ 95%] Downloading update (87302 of 90458 KB)...

2024/02/13 13:05:51,stdout,[ 93%] Downloading update (86010 of 90458 KB)...

2024/02/13 13:05:50,stdout,[ 92%] Downloading update (84760 of 90458 KB)...

2024/02/13 13:05:50,stdout,[ 91%] Downloading update (83377 of 90458 KB)...

2024/02/13 13:05:50,stdout,[ 90%] Downloading update (82647 of 90458 KB)...

2024/02/13 13:05:50,stdout,[ 89%] Downloading update (82008 of 90458 KB)...

2024/02/13 13:05:49,stdout,[ 87%] Downloading update (80711 of 90458 KB)...

2024/02/13 13:05:49,stdout,[ 86%] Downloading update (79355 of 90458 KB)...

2024/02/13 13:05:49,stdout,[ 85%] Downloading update (78131 of 90458 KB)...

2024/02/13 13:05:49,stdout,[ 83%] Downloading update (76902 of 90458 KB)...

2024/02/13 13:05:48,stdout,[ 82%] Downloading update (75626 of 90458 KB)...

2024/02/13 13:05:48,stdout,[ 80%] Downloading update (74375 of 90458 KB)...

2024/02/13 13:05:48,stdout,[ 79%] Downloading update (72991 of 90458 KB)...

2024/02/13 13:05:48,stdout,[ 77%] Downloading update (71720 of 90458 KB)...

2024/02/13 13:05:47,stdout,[ 76%] Downloading update (70450 of 90458 KB)...

2024/02/13 13:05:47,stdout,[ 75%] Downloading update (69180 of 90458 KB)...

2024/02/13 13:05:47,stdout,[ 73%] Downloading update (67869 of 90458 KB)...

2024/02/13 13:05:47,stdout,[ 72%] Downloading update (66608 of 90458 KB)...

2024/02/13 13:05:46,stdout,[ 70%] Downloading update (65364 of 90458 KB)...

2024/02/13 13:05:46,stdout,[ 69%] Downloading update (64181 of 90458 KB)...

2024/02/13 13:05:46,stdout,[ 68%] Downloading update (62870 of 90458 KB)...

2024/02/13 13:05:46,stdout,[ 66%] Downloading update (61697 of 90458 KB)...

2024/02/13 13:05:45,stdout,[ 63%] Downloading update (59771 of 90458 KB)...

2024/02/13 13:05:45,stdout,[ 60%] Downloading update (57350 of 90458 KB)...

2024/02/13 13:05:45,stdout,[ 57%] Downloading update (54839 of 90458 KB)...

2024/02/13 13:05:45,stdout,[ 55%] Downloading update (52355 of 90458 KB)...

2024/02/13 13:05:44,stdout,[ 52%] Downloading update (49995 of 90458 KB)...

2024/02/13 13:05:44,stdout,[ 49%] Downloading update (47558 of 90458 KB)...

2024/02/13 13:05:44,stdout,[ 46%] Downloading update (45172 of 90458 KB)...

2024/02/13 13:05:44,stdout,[ 44%] Downloading update (42490 of 90458 KB)...

2024/02/13 13:05:43,stdout,[ 41%] Downloading update (40017 of 90458 KB)...

2024/02/13 13:05:43,stdout,[ 38%] Downloading update (37500 of 90458 KB)...

2024/02/13 13:05:43,stdout,[ 36%] Downloading update (35177 of 90458 KB)...

2024/02/13 13:05:43,stdout,[ 33%] Downloading update (32726 of 90458 KB)...

2024/02/13 13:05:42,stdout,[ 30%] Downloading update (30178 of 90458 KB)...

2024/02/13 13:05:42,stdout,[ 27%] Downloading update (27628 of 90458 KB)...

2024/02/13 13:05:42,stdout,[ 24%] Downloading update (24994 of 90458 KB)...

2024/02/13 13:05:42,stdout,[ 22%] Downloading update (22594 of 90458 KB)...

2024/02/13 13:05:41,stdout,[ 19%] Downloading update (20114 of 90458 KB)...

2024/02/13 13:05:41,stdout,[ 16%] Downloading update (17608 of 90458 KB)...

2024/02/13 13:05:41,stdout,[ 13%] Downloading update (15075 of 90458 KB)...

2024/02/13 13:05:41,stdout,[ 10%] Downloading update (12482 of 90458 KB)...

2024/02/13 13:05:40,stdout,[  6%] Downloading update (9642 of 90458 KB)...

2024/02/13 13:05:40,stdout,[  2%] Downloading update (6166 of 90458 KB)...

2024/02/13 13:05:40,stdout,[  0%] Downloading update (2271 of 90458 KB)...

2024/02/13 13:05:40,stdout,[  0%] Downloading update (0 of 90458 KB)...

2024/02/13 13:05:39,stdout,[  0%] Checking for available update...

2024/02/13 13:05:39,stdout,ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".

2024/02/13 13:05:39,stdout,Redirecting stderr to '/root/Steam/logs/stderr.txt'

2024/02/13 13:05:39,stdout,steam.sh

2024/02/13 13:05:39,stdout,steamcmd.sh

2024/02/13 13:05:39,stdout,linux32/steamcmd

2024/02/13 13:05:39,stdout,linux32/libstdc++.so.6

2024/02/13 13:05:39,stdout,linux32/

2024/02/13 13:05:06,stdout,>>> Setting up WineConfig and waiting 15 seconds

2024/02/13 13:05:06,stdout,>>> Setting up Wine in bashrc

2024/02/13 13:05:06,stdout,>>> Checking if Wine is set in bashrc

2024/02/13 13:05:06,stdout,>>> Doing a fresh install of the gameserver

```

**Comment by PontyJohnty** [comment]
Have you tried volume mounting rather than bind mounting?

**Comment by Inazumaa** [comment]
> Have you tried volume mounting rather than bind mounting?

I'm not entirely sure what you mean but according to the settings (pictured) I am using volumes mapped to /docker/sonsoftheforest/

**Comment by jammsen** [comment]
I dont own a Synlogy, i dont know how to help on this edge-case, sorry. Maybe others in the community do.

**Comment by gitzec** [comment]
If the NAS does not allow binary execution on the volume you mapped into your container you have a similar issue as I had: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/issues/25

Your first error message generated by Wine points to this direction.
It says it cannot run: `/sonsoftheforest/SonsOfTheForestDS.exe`

Best would be to use the nas internal paths. But I am a QNAP user and do not know how a Synology handles where the shares' data is physically located.

**Comment by Inazumaa** [comment]
> Is your /sonsoftheforest folder outside of the docker folder? I.e. seperate in the volume?

Yes it is.

**Comment by PontyJohnty** [comment]
Interesting, I might try this myself, thank you!

**Comment by jammsen** [comment]
Closind this as complete, Thanks @Inazumaa
