### ISSUE TITLE
Server does not start anymore

### ISSUE THREAD

**Issue by heusmich** [jammsen/docker-sons-of-the-forest-dedicated-server#40]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Hi,

I´m not sure if this problem exists since the 1.0 update for SotF because I didn´t play the game for a few weeks now or if this is caused by something else, but currently I can´t connect to the server anymore. It worked in the past.
When I start the server with "docker-compose up, I can see that the server start stops with the following error message:

sons-of-the-forest-dedicated-server | #DSE [Self-Tests] [Networking] UDP GamePort [7798] is closed. Please fix and restart.

But I didn´t close any ports, I don´t have a firewall active or something similar.
And my other game servers are running without any problem.
I also don´t see the server ingame.

I searched in the closed issues here and I found the info that I could add "SkipNetworkAccessibilityTest": true, to the dedicatedserver.cfg file.
I tried this and the server is really booting up after I added this to the config file and restarted the server.
I can also see it ingame, I can select it, I get the password prompt but the connection doesn´t work, the connection attempt stops after a few seconds.

Do you have an idea what I could do to solve this?

### Desired behavior

I need help to solve this port issue since I´m not able to connect to the SotF server anymore.

### Software setup

- OS: Ubuntu 22.04
- Docker: 24.0.5

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by heusmich** [comment]
Issue can be solved, problem found and resolved.

**Comment by jammsen** [comment]
Hey @heusmich - Please provide an answer with the solution, so others who want to search for the resolution, like you did, find one.
