### ISSUE TITLE
Changing ports does not change the ports

### ISSUE THREAD

**Issue by LeandroTheDev** [jammsen/docker-sons-of-the-forest-dedicated-server#43]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

The command to run the docker
docker run --rm -i -t -p 8766:8766/udp -p 27016:27016/udp -p 9700:9700/udp -v $(pwd)/steamcmd:/steamcmd -v $(pwd)/game:/sonsoftheforest --name sons-of-the-forest-dedicated-server jammsen/sons-of-the-forest-dedicated-server:latest

The command i use to change the 27016 ports to 27017
docker run --rm -i -t -p 8766:8766/udp -p 27017:27017/udp -p 9700:9700/udp -v $(pwd)/steamcmd:/steamcmd -v $(pwd)/game:/sonsoftheforest --name sons-of-the-forest-dedicated-server jammsen/sons-of-the-forest-dedicated-server:latest

### Desired behavior

Output
```
#DSL [Self-Tests] [Networking] Testing server ports against public ip 189.27.181.39...
#DSL [Self-Tests] [Networking] UDP GamePort [8766] is open.
#DSE [Self-Tests] [Networking] UDP QueryPort [27016] is closed. Please fix and restart.
#DSL [Self-Tests] [Networking] UDP BlobSyncPort [9700] is open.
#DSE [Self-Tests] [Networking] Some ports are closed or already in use and the game server will not be ac
cessible. You may need to setup port forwarding and open them in your firewall, or change port numbers if
 they are used by some other software. Alternatively, consider using the LanOnly configuration if you did
n't intend to make your server public. Please fix and restart.
```

### To Reproduce

- Just run with different ports

### Software setup

- OS: Arch 
- Docker: Docker from arch repository

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by gitzec** [comment]
It is
- external:internal

Try to only change external port

**Comment by jammsen** [comment]
Hey @LeandroTheDev - Yes @gitzec is right, you only change the external ports, the internal are only for internal usage and dont need to be changed from you.
