### ISSUE TITLE
Trouble with port fowarding

### ISSUE THREAD

**Issue by sbasepa** [jammsen/docker-sons-of-the-forest-dedicated-server#46]
### Have you read the Important information text above

- [x] Yes i did

### Current behavior

Playing on Lan works great but when I try to port foward it dosnt work on the public ip

### Desired behavior

I want it to work anywhere

### Software setup

- OS:
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by TheRealLifeBasti** [comment]
Which router do you have?

**Comment by sbasepa** [comment]
It’s from tplink

**Comment by TheRealLifeBasti** [comment]
@sbasepa sorry but i can't hlep you, my router is from telekom so ..............................

**Comment by jammsen** [comment]
Sorry - my bad had the wrong tab open to inactivity close. Reopened it again

**Comment by sbasepa** [comment]
![image](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/83522814/dc5145b9-497d-4638-9459-0633425d059d)
Sorry for taking so long. Thank you for your patience and help

**Comment by sbasepa** [comment]
Now the container wont even work on LAN (it did when I started the post) here is my docker compose file
![image](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/83522814/d54c9372-4fec-44a5-a207-c52d1a93ba46)
How can i enable active networking checks?

**Comment by jammsen** [comment]
> I had to get some help from copilot to point this out because English is not my native language...:
> 
> I appreciate your engagement with this project and your efforts to resolve the issue you’re facing. However, it’s important to note that the purpose of this GitHub Issues section is to address problems specifically related to the project itself.
> 
> The issue you’re encountering seems to be more related to a basic understanding of Docker and networking, which are prerequisites for running this project successfully. There are numerous resources available online, including Docker’s own documentation and various networking tutorials, that can help you gain a better understanding of these concepts.
> 
> While I’m more than happy to assist with issues directly related to the project, I encourage you to leverage these resources for your current problem. This will not only help you resolve your immediate issue but also equip you with the knowledge to troubleshoot similar issues in the future.
> 
> Your initial question was: Are my port forwarding settings correct? Answer to this: Yes

Fully agree with @gitzec - We offer limited support, you need to be willing do you own part too.

**Comment by Sebastipole** [comment]
> ### Have you read the Important information text above
> 
>     * [x]  Yes i did
> 
> 
> ### Current behavior
> 
> Playing on Lan works great but when I try to port foward it dosnt work on the public ip
> ### Desired behavior
> 
> I want it to work anywhere
> ### Links to screenshots
> 
> _No response_
> ### To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> ### Software setup
> 
>     * OS:
> 
>     * Docker:
> 
> 
> ### Hardware setup
> 
>     * vCPU:
> 
>     * RAM:
> 
>     * Disk:
> 
> 
> ### Additional context
> 
> _No response_

Sorry for reviving a somewhat closed thread, I had the same issue, and for some unknown reason that I haven't been able to work out yet, the default ports the game required to be opened would not open at all.

I solved this by picking 3 random ports, opening them as per usual, confirming they were opening using standard PF'ing tester that they were open and changing the sotfDS config to use those 3 random ports instead of the default ports, this worked for me.
