### ISSUE TITLE
The server randomly shuts down after 20 minutes

### ISSUE THREAD

**Issue by TheRealLifeBasti** [jammsen/docker-sons-of-the-forest-dedicated-server#47]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I play a lot of Sons of the Forest with my friend, and now I thought I'd just set up a dedicated server. But unfortunately there is a problem because when I play on it, after a while it says "Host is not responding" and I get kicked out by the server with the message "The server has been shut down". When I then look at the Tmux session it says session ended. I only installed tmux because I thought the console had to be open like Minecraft, but the problem still hasn't been solved.

### Desired behavior

The only thing I changed is the name, password and target FPS.

### Software setup

- OS: Ubuntu
- Docker:

### Hardware setup

- vCPU: Intel Pentium
- RAM: 8GB
- Disk: 500Gb (idk what disk it is)

**Comment by jammsen** [comment]
Hey @TheRealLifeBasti 
There is a reason you should write SW/HW Setup ..... thats helps me, to actually help you ... if you dont do your job, but expect me to help you ... what then? Huh? Your RAM is very low for the first look, but if you dont deliver some facts, im gonna close this issue, sorry. If you want help, commit to it and take it seriously.

**Comment by TheRealLifeBasti** [comment]
Hi @jammsen I'm sorry for my mistake. Unfortunately I can't say anything specific about it because I don't know much about Linux, .... But I can try to take a screenshot of what is there.

Sorry about the unprofessionalism, this is my first time doing this.

Give me a few minutes and I'll have a screenshot.

**Comment by TheRealLifeBasti** [comment]
hey @jammsen, the server problems have been resolved.

**Comment by jammsen** [comment]
> hey @jammsen, the server problems have been resolved.

Hey @TheRealLifeBasti - Nice to hear, please provice a solution, so other who might have the same problem can learn from this.

**Comment by TheRealLifeBasti** [comment]
Hey @jammsen The probleme is that i dont know why it dosen't happend again. It just downloaded an update. So I think it was just an error that makes that kind of problem or an overload.

**Comment by jammsen** [comment]
Thanks for sharing that!

**Comment by jammsen** [comment]
Happy it works now!
