### ISSUE TITLE
HELP ERROR - DSL Incoming client connection with auth ticket

### ISSUE THREAD

**Issue by Danielkoscheck** [jammsen/docker-sons-of-the-forest-dedicated-server#49]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

 I receved a error  - DSL Incoming client connection with auth ticket

### Desired behavior

 I receved a error  - DSL Incoming client connection with auth ticket

### Links to screenshots

.

### To Reproduce

.

### Software setup

.

### Hardware setup

.

**Comment by jammsen** [comment]
Good morning, maybe this helps:
https://steamcommunity.com/app/1326470/discussions/0/4347732779396108217/

**Comment by Danielkoscheck** [comment]
Receive error "DSL inbound client connection with authentication ticket"

Ports 2016, 9700, 8766 open on the router.

The server is not listed in the game.


SETTINGS:

{
  "IP Address": "0.0.0.0",
  "GamePort": 8766,
  "QueryPort": 27016,
  "BlobSyncPort": 9700,
  "ServerName": "Children of the Forest Server - 100.1.1.102",
  "MaxPlayers": 4,
  "Password": "",
  "LanOnly": false,
  "SaveSlot": 1,
  "SaveMode": "Continue",
  "GameMode": "Normal",
  "SaveRange": 600,
  "IdleDayCycleSpeed": 0.0,
  "IdleTargetFramerate": 5,
  "ActiveTargetFramerate": 60,
  "LogFilesEnabled": false,
  "TimestampLogFilenames": true,
  "TimestampLogEntries": true,
  "SkipNetworkAccessibilityTest": false,
  "Game Settings": {},
  "CustomGameModeSettings": {}
}

**Comment by jammsen** [comment]
Again, read the link i posted.

**Comment by Danielkoscheck** [comment]
What is the solution to the topic in the link? @jammsen

**Comment by jammsen** [comment]
"SkipNetworkAccessibilityTest": true ?!?!?!?!??!

**Comment by Danielkoscheck** [comment]
SkipNetworkAccessibilityTest": true and false...Same error.  :(

As soon as it connects it is kicked, that error appears on the console.

connect 100.1.1.102:8766... connecting...and appears on the console server: incoming cliente connection with auth ticket ...Client disconnected

**Comment by jammsen** [comment]
Then this seems to be a networking or/and gameserver related question. Try the Steam-Forum for Sons of the Forest. Nothing what you wrote i can reproduce, it just works for me. But i havent had any informations anyways, because you really didnt provide any.

**Comment by jogerj** [comment]
This sounds like either the client is not logged in to Steam or the server could not authenticate the user via Steam servers. Make sure the Steam client is not set to offline (use invisible if you don't want to appear online).

**Comment by jammsen** [comment]
Closed by inactivity
