### ISSUE TITLE
Where is the archive?

### ISSUE THREAD

**Issue by VegetablCat** [jammsen/docker-sons-of-the-forest-dedicated-server#50]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When I logged into the server for the first time, I found that someone had built a house in it. I want to erase the archives and start over, or is there any way to have multiple archives at the same time?

### Desired behavior

none

### To Reproduce

none

### Software setup

none

### Hardware setup

none

**Comment by jammsen** [comment]
What are archives? Are you talking about savegames?

**Comment by VegetablCat** [comment]
Yes,i have found it in userdata/Saves/DedicatedServer/Multippayer
