### ISSUE TITLE
Can't find game server

### ISSUE THREAD

**Issue by VegetablCat** [jammsen/docker-sons-of-the-forest-dedicated-server#51]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I'm sure I have a public ip, and I have correctly set the port mapping and released the designated port, but I can't find the game server through ip direct connection, no matter whether I use the public IP or the LAN IP under the same router as the server.

### Desired behavior

i hope it can work correctly

### Links to screenshots

![e462d9c92b8f8f03fda281742e03c2f4](https://github.com/user-attachments/assets/789a3991-d979-4d94-849d-46a15e4538d9)
![dcd6428351541d0e615006cdbf43f1ba](https://github.com/user-attachments/assets/e0f3831b-75ba-4ed6-be23-c1123704e7c0)

### To Reproduce

no way

### Software setup

- OS:
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by VegetablCat** [comment]
> It should show up in the game's online server browser as dedicated server with the name you gave 
The online server browser is not displayed either.

**Comment by VegetablCat** [comment]
#DSL [Self-Tests] [Networking] Testing server ports against public ip (public ip)_...

#DSE [Self-Tests] [Networking] UDP GamePort [8766] is closed. Please fix and restart.

#DSE [Self-Tests] [Networking] UDP QueryPort [27016] is closed. Please fix and restart.

#DSE [Self-Tests] [Networking] UDP BlobSyncPort [9700] is closed. Please fix and restart.

#DSE [Self-Tests] [Networking] Some ports are closed or already in use and the game server will not be accessible. You may need 

to setup port forwarding and open them in your firewall, or change port numbers if they are used by some other software. Alterna

tively, consider using the LanOnly configuration if you didn't intend to make your server public. Please fix and restart.

#DSE [Self-Tests] Please restart the server.

I am quite sure that I have set up the correct port forwarding and have not occupied ports 8766, 27016 and 9700. Even if I turn on DMZ, I will be prompted as above.

**Comment by VegetablCat** [comment]
> #DSL [自检] [网络] 针对公共 IP （public ip） 测试服务器端口_...
> 
> #DSE [自检] [网络] UDP GamePort [8766] 已关闭。请修复并重新启动。
> 
> #DSE [自检] [网络] UDP QueryPort [27016] 已关闭。请修复并重新启动。
> 
> #DSE [自检] [网络] UDP BlobSyncPort [9700] 已关闭。请修复并重新启动。
> 
> #DSE [自检] [网络] 某些端口已关闭或已在使用中，无法访问游戏服务器。您可能需要
> 
> 设置端口转发并在防火墙中打开它们，或者更改端口号（如果它们被其他软件使用）。奥特纳
> 
> 如果您不打算公开服务器，请考虑使用 LanOnly 配置。请修复并重新启动。
> 
> #DSE 【自检】请重启服务器。
> 
> 我非常确定我已经设置了正确的端口转发，并且没有占用端口 8766、27016 和 9700。即使我打开 DMZ，我也会收到如上所述的提示。

and i have closed firewall

**Comment by VegetablCat** [comment]
> 如果您正确设置了所有端口转发...你有公共 ipv4 地址吗？
I'm sure I have a public ip, and I can SSH to the server from other places, and I used to be able to play on the server normally, but not since I changed the router to another room.
And even if I don't have a public ip, I should be able to connect to the server through a LAN ip, but I still can't. I'm also quite sure that the port is not occupied.

**Comment by VegetablCat** [comment]
> 请将您的设置与此 scetch 进行比较：
> 
> 1. 你有某种电缆与你的ISP在另一端
> 2. 您的 ISP 为您提供了一个设备（哪个？），可以将电缆变成以太网端口
> 3. 您使用路由器（哪个？）在LAN和从ISP获得的公共IPv4之间执行NAT操作
> 4. 您在路由器上配置了端口转发，以便将路由器的传入连接转发到 Docker 主机
> 5. 您的 docker 主机位于此 LAN（静态 IP 或静态 DHCP 租约）内，并且可以访问 Internet
> 6. 您的 Docker 主机接受给定端口上的传入请求。
> 7. 您的 Docker 容器在此主机上运行，并且具有给定端口的传入连接的端口转发

I am sure that my configuration meets the above conditions and I can connect to the server normally before I move the router.

**Comment by VegetablCat** [comment]
![246f61fc070196da45e57928796359dd](https://github.com/user-attachments/assets/889a330d-48bb-4a78-90af-eaa73c15b4ef)
![37c0c5318ecb2d7dbd77517a0a59a027](https://github.com/user-attachments/assets/c97cff65-8885-4b83-b48c-b508d9fb619c)
![5853bd0ae3f60a21a930f18ee2828066](https://github.com/user-attachments/assets/c1871760-3a7e-465d-9b09-f9378a6bb732)
![cbd19458a2284679a448a887599f5059](https://github.com/user-attachments/assets/58e9be2c-691e-4cce-97e1-c38e42e62db3)
![97994247caade5c3272287d2a3566113](https://github.com/user-attachments/assets/a0be2817-acd0-40ba-acdb-ce8024847c30)
![aa23e36a3cd4b5b5d70b84c99960b55c](https://github.com/user-attachments/assets/61e59ff7-eadf-48e3-bd67-fb02f253a471)
These are my configurations (only one of them is captured in three port forwarding, and the other two port configurations are similar to this one). I'm sure there is no problem, because I can play PalWorld running on the same server normally, and I can also access my server on the external network.

**Comment by jogerj** [comment]
Your setup looks really weird. I'm guessing from your setup, you have an ISP modem/router at 192.168.1.1 that hosts the DHCP server, then an access point at 192.168.1.3? In which case then the port forwarding should be configured at the ISP router and the repeater/access point left alone. The port forwarding rule should target the host IP address (your PC's internal IP), not the access point's.

As for why PalWorld works, you should be able to replicate the same port forwarding setup as PalWorld and it should work.

Usually when port forwarding doesn't work it's one of these scenarios:
1. Incorrect configuration: wrong target IP/ports. 
2. you're on VPN (for obvious reasons won't work, at least not from public net)
3. your ISP only gives you IPv6 (DS Lite, shared IPv4) -> in your case it doesn't seem like it
4. your ISP blocks ports by default -> you need to contact your ISP about it

If you're sure the ports should be accessible anyway or you have workaround to let you access the server (e.g. via 4in6 tunnel),  you can disable the self tests in `dedicatedserver.cfg`:

```
  "SkipNetworkAccessibilityTest": true,
  "LanOnly": true,
```

Setting LanOnly will also prevent your server to be publicly listed on servers list (you need to use direct connect)

**Comment by VegetablCat** [comment]
> Your setup looks really weird. I'm guessing from your setup, you have an ISP modem/router at 192.168.1.1 that hosts the DHCP server, then an access point at 192.168.1.3? In which case then the port forwarding should be configured at the ISP router and the repeater/access point left alone. The port forwarding rule should target the host IP address (your PC's internal IP), not the access point's.
> 
> As for why PalWorld works, you should be able to replicate the same port forwarding setup as PalWorld and it should work.
> 
> Usually when port forwarding doesn't work it's one of these scenarios:
> 
> 1. Incorrect configuration: wrong target IP/ports.
> 2. you're on VPN (for obvious reasons won't work, at least not from public net)
> 3. your ISP only gives you IPv6 (DS Lite, shared IPv4) -> in your case it doesn't seem like it
> 4. your ISP blocks ports by default -> you need to contact your ISP about it
> 
> If you're sure the ports should be accessible anyway or you have workaround to let you access the server (e.g. via 4in6 tunnel), you can disable the self tests in :`dedicatedserver.cfg`
> 
> ```
>   "SkipNetworkAccessibilityTest": true,
>   "LanOnly": true,
> ```
> 
> Setting LanOnly will also prevent your server to be publicly listed on servers list (you need to use direct connect)

I set the router (192.168.1.3/192.168.3.1) to DMZ in the ISP modem, but my computer and server are connected to the router (192.168.3.1), that is, in the same LAN, even so, I can't connect to the server. However, it is very strange that I downloaded someone else's image of the dedicated server for the children of the forest and ran it without any problem. However, once the router network cable is loosened and reconnected, even if the container is completely deleted and the directory is mounted and the container is rebuilt, it will report that the port is closed.

**Comment by jammsen** [comment]
Im not sure from reading, is this issue solved or still ongoing? @VegetablCat

**Comment by jogerj** [comment]
Maybe the router which your computer is connected to is on a different NAT. The router needs to be set as an access point only without its own DHCP server (use DHCP server from main modem/router)

**Comment by milobluebell** [comment]
> Maybe the router which your computer is connected to is on a different NAT. The router needs to be set as an access point only without its own DHCP server (use DHCP server from main modem/router)

1. Means it must use `host` mode in docker, right?
2. But After i installed docker and everything ok,it shown me"cannot get public ip from steam" on my tencent-cloud vps

**Comment by jogerj** [comment]
> Means it must use `host` mode in docker, right?

Not necessary. As long as you specify the exposed ports in docker, the ports are exposed to the host machine (and assuming default firewall settings, the private network). The game server is then accessible at `your-host-machine-ip-address:8766`. Forward your ports to public internet then it's accessible at `your-public-ip:8766`

@milobluebell your issue might be different since it's a VPS setup. You should start a new issue including your configs and setup description.

**Comment by VegetablCat** [comment]
> Im not sure from reading, is this issue solved or still ongoing? @VegetablCat

it still doesn't work,

**Comment by VegetablCat** [comment]
> Im not sure from reading, is this issue solved or still ongoing? @VegetablCat

Although I put the server and the client in the same LAN (under the same router), the client still can't find the server through the LAN ip of the server, but the servers of other games can run normally.

**Comment by VegetablCat** [comment]
> Maybe the router which your computer is connected to is on a different NAT. The router needs to be set as an access point only without its own DHCP server (use DHCP server from main modem/router)

I'm sure they are under the same network segment, and the server running other games on the same server is still normal, but only the server of the son of the forest can't run normally.

**Comment by jogerj** [comment]
This seems like the problem basically comes down to an issue with your port forwarding setup and not the dedicated server container. Steps you can try to test and troubleshoot:
1. On the host machine `docker run -it --rm -p "8766:8766/udp" networkstatic/iperf3 -s -p 8766`
2. Then run iperf as client `docker run -it --rm networkstatic/iperf3 -c <your-public-ip> -p 8766 -4 -u` -> get ip from e.g. `curl -4 checkip.amazonaws.com`
3. If it fails, then the issue is with your port forwarding setup. Repeat for port 9700 and 27016

**Comment by VegetablCat** [comment]
> This seems like the problem basically is an issue with your port forwarding setup and not the dedicated server container. Steps you can try to test and troubleshoot:
> 
> 1. On the host machine `docker run -it --rm -p "8766:8766/udp" networkstatic/iperf3 -s -p 8766`
> 2. Then run iperf as client  -> get ip from e.g. `docker run -it --rm networkstatic/iperf3 -c <your-public-ip> -p 8766 -4 -u``curl -4 checkip.amazonaws.com`
> 3. If it fails, then the issue is with your port forwarding setup. Repeat for port 9700 and 27016
> 
> Also as I mentioned previously, your setup looks like you have double NAT. You need to port forward on both routers serving as gateways or configure the secondary router to use the same DHCP (so they can be on the same NAT layer), then port forward once at the main router.

![QQ_1722997063407](https://github.com/user-attachments/assets/dd645771-344c-4af0-b7ed-cd1d7ad218ff)
This should not be a problem of port forwarding. First of all, I have configured the server of other games, and the configuration of the son of the forest is the same as them, but other game servers can operate normally, except the son of the forest. Secondly, my client and server can't access the child server of the forest under the same router, which means it's not a port forwarding problem.

**Comment by VegetablCat** [comment]
![c9a929bc1a47277b31acf0e82eec5ec6](https://github.com/user-attachments/assets/4d974a9b-98d2-47d6-82f2-9d588134750b)

**Comment by jogerj** [comment]
> ![c9a929bc1a47277b31acf0e82eec5ec6](https://private-user-images.githubusercontent.com/158834949/355653170-4d974a9b-98d2-47d6-82f2-9d588134750b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjMxOTYsIm5iZiI6MTcyMzcyMjg5NiwicGF0aCI6Ii8xNTg4MzQ5NDkvMzU1NjUzMTcwLTRkOTc0YTliLTk4ZDItNDdkNi04MmYyLTlkNTg4MTM0NzUwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMTU0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTA0ZGY5Mzk0ZWIwNzViZDliYTQzZWE4NGYwYjhhZGQzZmRjNzkwZjE1YmM3NTY0ZjI5YzM0ZTQ4MzAyY2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yle7hSOQCXiVz5VRgCXpncul-XQNDyXcbiKa7xIb15M)

You have a double NAT. Otherwise your router wouldn't have two IP addresses assigned.

**Comment by jammsen** [comment]
Closed because of inactivity
