### ISSUE TITLE
Missing file permissions

### ISSUE THREAD

**Issue by OGcodifier** [jammsen/docker-sons-of-the-forest-dedicated-server#54]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

After following the guide I get this error repeatedly after docker-compose up.  It tries a few times, each iteration with the error
**ERROR! Failed to install app '2465200' (Missing file permissions)**.    Fresh install of Debian 12 (bookworm).  This is a fresh install, it has never worked before.

> sotf-server    | >>> Doing an update of the gameserver
> sotf-server    | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> sotf-server    | Redirecting stderr to '/root/Steam/logs/stderr.txt'
> sotf-server    | Logging directory: '/root/Steam/logs'
> sotf-server    | [  0%] Checking for available updates...
> sotf-server    | [----] Verifying installation...
> sotf-server    | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922
> sotf-server    | -- type 'quit' to exit --
> sotf-server    | Loading Steam API...OK
> sotf-server    | @sSteamCmdForcePlatformType windows
> sotf-server    | "@sSteamCmdForcePlatformType" = "windows"
> sotf-server    | force_install_dir /sonsoftheforest
> sotf-server    |
> sotf-server    | Connecting anonymously to Steam Public...OK
> sotf-server    | Waiting for client config...OK
> sotf-server    | Waiting for user info...OK
> sotf-server    | app_update 2465200 validate
> sotf-server    | ERROR! Failed to install app '2465200' (Missing file permissions)
> sotf-server    | quit
> sotf-server    | 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> sotf-server    | 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> sotf-server    | 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> sotf-server    | 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> sotf-server    | >>> Starting the gameserver
> sotf-server    | wine: failed to open "/sonsoftheforest/SonsOfTheForestDS.exe": c0000135

### Desired behavior

Server to start

### To Reproduce

1. sudo docker-compose up in the /home/username/docker directory

### Software setup

- OS: Debian 12
- Docker: 20.10.24

### Hardware setup

- vCPU: 1 (4 cores)
- RAM: 10GB
- Disk: 32GB

**Comment by jammsen** [comment]
Hey @OGcodifier any network mapped storage involved?
Im missing the docker-compose file to look into that.

**Comment by OGcodifier** [comment]
Hey @jammsen I don't have any network mapping, all local.  

Did some internet sleuthing and found a similar problem regarding steam not using the proper $HOME directory, link below.  

https://github.com/thijsvanloef/palworld-server-docker/issues/551#issuecomment-2214454801


So I set my docker-compose file like below:
>    environment:
>     ALWAYS_UPDATE_ON_START: 1
>      _HOME: /home/steam_

Now the shell shows this: 

>sotf-server    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
>sotf-server    | Logging directory: '/home/steam/Steam/logs'

Instead of this:

>sotf-server | Redirecting stderr to '/root/Steam/logs/stderr.txt'
>sotf-server | Logging directory: '/root/Steam/logs'

Everything downloaded, looks like the workaround worked.  Thanks for the quick reply, I am new to docker and still fumbling my way through.

**Comment by jammsen** [comment]
I agree with @thijsvanloef that is really weird.
