### ISSUE TITLE
Issue with authentication?

### ISSUE THREAD

**Issue by Sirchacha2** [jammsen/docker-sons-of-the-forest-dedicated-server#56]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

failed to authenticate after restart, Damon asking for docker login

### Desired behavior

In running a mini PC with an Intel 10400t on Linux mint, I followed this guide

https://youtu.be/vqf8gYcZC5E?si=IPuIhxKEO4WFBTW-

 which clones your repository into /home/sotf. It was working fine until I restarted, now it's saying "Error response from daemon: pull access denied for sotf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."

I'm still new to docker so I'm not sure what this means or how to rectify it.

### To Reproduce

1. Run the script to install your dedicated as found in the video above, 
2. restart the computer
3. Try to run sudo docker run [name of container].

### Software setup

- OS: Linux mint 22
- Docker: 27

### Hardware setup

- vCPU: I5-10400t
- RAM: 32gb 3200 DDR4
- Disk: 1TB 2.5 SSD.

**Comment by jammsen** [comment]
Have you tried the manual on the wiki or on my readme?
Wiki: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/wiki
Readme: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server#what-you-need-to-run-this

**Comment by Sirchacha2** [comment]
> Maybe ask the creator of the video when using a different way to install as described in this github...

I did, he was super quick to respond to a more general question of something he didn't cover in the video but I replied back to him with my current situation and he hasn't responded yet. I asked a friend who is decently familiar with Linux and docker and he said might be worth it to try on here.

**Comment by Sirchacha2** [comment]
> Have you tried the manual on the wiki or on my readme?
> Wiki: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/wiki
> Readme: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server#what-you-need-to-run-this

Hey thanks for the reply, is there any way to purge this install and try again with your instructions? Is it just a matter of using portainer to stop it and then delete the container? I'm down to just try over again since I didn't even get to the point where anyone was online to test it out.

**Comment by Sirchacha2** [comment]
> Have you tried the manual on the wiki or on my readme? Wiki: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/wiki Readme: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server#what-you-need-to-run-this

hey so i followed all of the instructions but its getting stuck at the docker compose step, i checked to see if i had the plugin and i do but its sying docker-compse command not found?

**Comment by jammsen** [comment]
> > Have you tried the manual on the wiki or on my readme? Wiki: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/wiki Readme: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server#what-you-need-to-run-this
> 
> hey so i followed all of the instructions but its getting stuck at the docker compose step, i checked to see if i had the plugin and i do but its sying docker-compse command not found?

No idea what you are talking about, what plugin? Why no error logs?
