### ISSUE TITLE
shader error during startup server

### ISSUE THREAD

**Issue by ad4mny** [jammsen/docker-sons-of-the-forest-dedicated-server#60]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

![image](https://github.com/user-attachments/assets/4159c20b-77a4-44f5-91a0-b143ad270ff5)

the sample image shown the startup is killed during deployment.

server config used are default except servername, password and LAN set to true.

### Desired behavior

Server should be able to start up in LAN.

### To Reproduce

1. Run the docker deployment code on the installation page.

### Software setup

- OS: Debian 12 latest (bookworm)
- Docker: Docker latest

### Hardware setup

- vCPU: intel core i5-6500T
- RAM: 8GB ddr4
- Disk: 128gb

**Comment by jammsen** [comment]
You dont have enough RAM, see Wiki for Requirement and read the Readme
https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/wiki#%EF%B8%8F-requirements

**Comment by TheKogoro** [comment]
I have same shaders errors but the Server run on 40Gb Ram so it isnt the Ram in my case. Note the Server is running and can be joint and play on it. Exept somes random little graphical glitch, it Seem working. (Idk If the graphical glitch is due from thoses errors or it present in all dédicaces Server).

Note also, when i Shutdown from Portainer, the container exit with code 137.

**Comment by jammsen** [comment]
@TheKogoro The Shader Warnings and Errors are always there, look at the logs of the first image i wrote for TheForest it was the same there. 

The problem @ad4mny is facing that the server is beeing "killed" look at the last line and then at his Hardware-Setup in which he lists his entire system has only 8GB RAM, the server alone needs 10GB to run smoothly. So im guessing he tries to start the server, Docker and the DS use a lot of RAM and the OOM-Killer from the Linux Kernel comes around kills the process.

And if @ad4mny doesnt answers anymore, im gonna inactivity-close this issue.

**Comment by jammsen** [comment]
> I have same shaders errors but the Server run on 40Gb Ram so it isnt the Ram in my case. Note the Server is running and can be joint and play on it. Exept somes random little graphical glitch, it Seem working. (Idk If the graphical glitch is due from thoses errors or it present in all dedicated Server).
> 
> Note also, when i Shutdown from Portainer, the container exit with code 137.

Also im pretty sure that some Shader-Erros are even thrown in the native Windows GUI Blackscreen version of the DS, might have changed, but when i tried this the last time, about 6 months ago under native Windows 10 for testing with an GPU in the system, it was like that, even under optimal conditions.

**Comment by TheKogoro** [comment]
> > I have same shaders errors but the Server run on 40Gb Ram so it isnt the Ram in my case. Note the Server is running and can be joint and play on it. Exept somes random little graphical glitch, it Seem working. (Idk If the graphical glitch is due from thoses errors or it present in all dedicated Server).
> > Note also, when i Shutdown from Portainer, the container exit with code 137.
> 
> Also im pretty sure that some Shader-Erros are even thrown in the native Windows GUI Blackscreen version of the DS, might have changed, but when i tried this the last time, about 6 months ago under native Windows 10 for testing with an GPU in the system, it was like that, even under optimal conditions.

Thanks for an answer, so it's totally normal that i See all wheses warning/error on logs . 

For the Shutdown turning into error code 137, it is also normal operation or i need to put somes variable (i use Portainer).

**Comment by ad4mny** [comment]
Alright thanks for the details regarding the ram information, will upgrade my ram first and see how it goes.

**Comment by jammsen** [comment]
> > > I have same shaders errors but the Server run on 40Gb Ram so it isnt the Ram in my case. Note the Server is running and can be joint and play on it. Exept somes random little graphical glitch, it Seem working. (Idk If the graphical glitch is due from thoses errors or it present in all dedicated Server).
> > > Note also, when i Shutdown from Portainer, the container exit with code 137.
> > 
> > 
> > Also im pretty sure that some Shader-Erros are even thrown in the native Windows GUI Blackscreen version of the DS, might have changed, but when i tried this the last time, about 6 months ago under native Windows 10 for testing with an GPU in the system, it was like that, even under optimal conditions.
> 
> Thanks for an answer, so it's totally normal that i See all wheses warning/error on logs .
> 
> For the Shutdown turning into error code 137, it is also normal operation or i need to put somes variable (i use Portainer).

@TheKogoro look here https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/issues/4 in the Pastebin and search for Shader and be surprised how much browser-coloring exists for search-keywords 😄 - This is SOTF from about 16-18 months ago.

About the Exit-Code 137 with Portainer, a) sorry i missed this and b) i dont really know, i dont recommend Portainer and i dont use it anymore, im using Dockge, because Portainer caused so many problems in all my images from TF, SOTF to Palworld. It might be okay, it might be caused by Portainer im not really sure, but if the server shuts down savely and your savegame is okay, i would assume its okay?

If you want you can ask in the Discord https://discord.gg/7tacb9Q6tj
I forgot to add this community Discord-Link to TF and SOTF, but Palworld has it.

**Comment by jammsen** [comment]
Added it now to TF and SOTF

**Comment by TheKogoro** [comment]
> > > > I have same shaders errors but the Server run on 40Gb Ram so it isnt the Ram in my case. Note the Server is running and can be joint and play on it. Exept somes random little graphical glitch, it Seem working. (Idk If the graphical glitch is due from thoses errors or it present in all dedicated Server).
> > > > Note also, when i Shutdown from Portainer, the container exit with code 137.
> > > 
> > > 
> > > Also im pretty sure that some Shader-Erros are even thrown in the native Windows GUI Blackscreen version of the DS, might have changed, but when i tried this the last time, about 6 months ago under native Windows 10 for testing with an GPU in the system, it was like that, even under optimal conditions.
> > 
> > 
> > Thanks for an answer, so it's totally normal that i See all wheses warning/error on logs .
> > For the Shutdown turning into error code 137, it is also normal operation or i need to put somes variable (i use Portainer).
> 
> @TheKogoro look here #4 in the Pastebin and search for Shader and be surprised how much browser-coloring exists for search-keywords 😄 - This is SOTF from about 16-18 months ago.
> 
> About the Exit-Code 137 with Portainer, a) sorry i missed this and b) i dont really know, i dont recommend Portainer and i dont use it anymore, im using Dockge, because Portainer caused so many problems in all my images from TF, SOTF to Palworld. It might be okay, it might be caused by Portainer im not really sure, but if the server shuts down savely and your savegame is okay, i would assume its okay?
> 
> If you want you can ask in the Discord https://discord.gg/7tacb9Q6tj I forgot to add this community Discord-Link to TF and SOTF, but Palworld has it.

I have also Palworld Server, on Palworld it work Well and Shutdown proprely. But for Sons of the forest, it was ok even If it Shutdown with error code 137, i can boot and load my save without problem.

**Comment by jammsen** [comment]
Seems to be fine then 👍

**Comment by jammsen** [comment]
> Alright thanks for the details regarding the ram information, will upgrade my ram first and see how it goes.

@ad4mny - Feel free to reach out again in this issue, if you tried more RAM and let me know if that fixed that problem.

**Comment by TheKogoro** [comment]
> Savegame should be easy to transfer yes.

Yes, it's very easy, just copy the folder in the userdata of the Server that startig with many 0 to the same location of the new Server (For me it's: /Docker/sons-of-the-forest/userdata/Saves/DedicatedServer/Multiplayer/0000000001) (same procedure for Palworld). Easy and work without problem 👌🏻👍🏻

**Comment by jammsen** [comment]
I always just copy paste the Saves directory, never have once a problem with that.
