### ISSUE TITLE
Software based server failures not throwing exit code

### ISSUE THREAD

**Issue by Brutalbeard** [jammsen/docker-sons-of-the-forest-dedicated-server#9]
Came back to my kubernetes cluster and the container was running. Checked out logs though, and the server had crashed and put a crash report in a temp folder (ephemeral so i couldn't pull it). 

If the container threw like an exit code (1) then the container would auto restart, but it doesn't seem to be doing that. 

Think you could put in some kind of check for it? 

Otherwise, great work on this docker image it's running really well.

**Comment by jammsen** [comment]
This should be happening according to https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L84 it does that for me when i tried and tested earlier versions with defective configs, where the server would exit crically.

**Comment by jammsen** [comment]
If you use docker run it should exit if you use my DC-File then it should restart the server as "always" setting

**Comment by jammsen** [comment]
@Brutalbeard Ping?
